INSERT INTO Podcast VALUES (1, 'Teknoloji Dünyasý', 'Ahmet Yýlmaz', 'Güncel teknoloji haberleri ve incelemeleri.', 'Teknoloji');
INSERT INTO Podcast VALUES (2, 'Giriþimcilik Rehberi', 'Elif Koyuncu', 'Yeni baþlayanlar için giriþimcilik tavsiyeleri.', 'Ýþ');
INSERT INTO Podcast VALUES (3, 'Tarih Sohbetleri', 'Mehmet Demir', 'Tarihin ilginç olaylarý ve figürleri.', 'Tarih');
INSERT INTO Podcast VALUES (4, 'Saðlýklý Yaþam', 'Ayþe Öztürk', 'Saðlýk ve beslenme üzerine güncel bilgiler.', 'Saðlýk');
INSERT INTO Podcast VALUES (5, 'Kitap Kulübü', 'Burcu Arslan', 'Haftanýn kitap önerileri ve yorumlarý.', 'Edebiyat');
INSERT INTO Podcast VALUES (6, 'Spor Günlüðü', 'Caner Yýldýz', 'Futbol ve diðer spor dallarýndan haberler.', 'Spor');
INSERT INTO Podcast VALUES (7, 'Sinema Keyfi', 'Deniz Çelik', 'Film incelemeleri ve sektörel geliþmeler.', 'Sinema');
INSERT INTO Podcast VALUES (8, 'Kariyer Atölyesi', 'Merve Kaya', 'Kariyer planlama ve iþ hayatý tavsiyeleri.', 'Ýþ');
INSERT INTO Podcast VALUES (9, 'Yemek Tarifleri', 'Fatma Demir', 'Lezzetli ve pratik yemek tarifleri.', 'Yemek');
INSERT INTO Podcast VALUES (10, 'Müzik Hikayeleri', 'Serkan Aksoy', 'Ünlü müzik sanatçýlarýnýn yaþam öyküleri.', 'Müzik');
INSERT INTO Podcast VALUES (11, 'Kiþisel Geliþim', 'Deniz Yýlmaz', 'Kiþisel geliþim ve motivasyon konuþmalarý.', 'Kiþisel Geliþim');
INSERT INTO Podcast VALUES (12, 'Dünya Haberleri', 'Emre Kaya', 'Güncel dünya haberleri ve analizleri.', 'Haber');
INSERT INTO Podcast VALUES (13, 'Psikoloji Notlarý', 'Ece Arslan', 'Psikoloji alanýndaki güncel araþtýrmalar.', 'Psikoloji');
INSERT INTO Podcast VALUES (14, 'Bilim ve Gelecek', 'Seda Yýldýz', 'Bilim dünyasýndan son geliþmeler.', 'Bilim');
INSERT INTO Podcast VALUES (15, 'Moda Sohbetleri', 'Nilay Çelik', 'Moda trendleri ve stil önerileri.', 'Moda');
INSERT INTO Podcast VALUES (16, 'Edebiyat Dünyasý', 'Selin Demir', 'Klasik ve modern edebiyat eserleri.', 'Edebiyat');
INSERT INTO Podcast VALUES (17, 'Finansal Piyasalar', 'Ali Yýlmaz', 'Borsa ve ekonomi analizleri.', 'Finans');
INSERT INTO Podcast VALUES (18, 'Gezginler Kulübü', 'Ayhan Çelik', 'Seyahat deneyimleri ve öneriler.', 'Seyahat');
INSERT INTO Podcast VALUES (19, 'Teknoloji Gündemi', 'Murat Demir', 'Teknolojideki son geliþmeler.', 'Teknoloji');
INSERT INTO Podcast VALUES (20, 'Motivasyon Zamaný', 'Zeynep Kaya', 'Günlük motivasyon ve baþarý hikayeleri.', 'Kiþisel Geliþim');
INSERT INTO Podcast VALUES (21, 'Gelecek Vizyonu', 'Fatih Demir', 'Teknolojinin geleceði ve yenilikler.', 'Teknoloji');
INSERT INTO Podcast VALUES (22, 'Kültür Sanat', 'Sibel Yýlmaz', 'Kültür ve sanat dünyasýndan haberler.', 'Sanat');
INSERT INTO Podcast VALUES (23, 'Saðlýk Rehberi', 'Ayþe Þahin', 'Saðlýklý yaþam tüyolarý ve öneriler.', 'Saðlýk');
INSERT INTO Podcast VALUES (24, 'Ekonomi Raporu', 'Emre Arslan', 'Ekonomi haberleri ve piyasa analizi.', 'Finans');
INSERT INTO Podcast VALUES (25, 'Dijital Pazarlama', 'Murat Kaya', 'Pazarlama stratejileri ve dijital trendler.', 'Ýþ');
INSERT INTO Podcast VALUES (26, 'Tarih Yolculuðu', 'Deniz Öztürk', 'Tarihin bilinmeyen yönleri.', 'Tarih');
INSERT INTO Podcast VALUES (27, 'Kitap Tavsiyeleri', 'Selin Aydýn', 'Haftalýk kitap önerileri.', 'Edebiyat');
INSERT INTO Podcast VALUES (28, 'Film Ýncelemesi', 'Serkan Yýldýz', 'Popüler filmler ve analizler.', 'Sinema');
INSERT INTO Podcast VALUES (29, 'Müzik Listesi', 'Ece Çelik', 'Güncel müzik listeleri ve yorumlar.', 'Müzik');
INSERT INTO Podcast VALUES (30, 'Kariyer Planý', 'Merve Arslan', 'Ýþ dünyasýnda baþarý için tavsiyeler.', 'Ýþ');
INSERT INTO Podcast VALUES (31, 'Yemek Keyfi', 'Fatma Yýlmaz', 'Lezzetli yemek tarifleri ve mutfak sýrlarý.', 'Yemek');
INSERT INTO Podcast VALUES (32, 'Psikoloji Sohbeti', 'Ece Þahin', 'Zihinsel saðlýk ve psikoloji üzerine.', 'Psikoloji');
INSERT INTO Podcast VALUES (33, 'Bilim Dünyasý', 'Seda Demir', 'Bilimsel geliþmeler ve yeni keþifler.', 'Bilim');
INSERT INTO Podcast VALUES (34, 'Moda Trendleri', 'Nilay Yýldýz', 'Sezonun moda haberleri ve önerileri.', 'Moda');
INSERT INTO Podcast VALUES (35, 'Finansal Strateji', 'Ali Demir', 'Kiþisel finans ve yatýrým önerileri.', 'Finans');
INSERT INTO Podcast VALUES (36, 'Seyahat Rehberi', 'Ayhan Yýlmaz', 'Dünyanýn dört bir yanýndan seyahat önerileri.', 'Seyahat');
INSERT INTO Podcast VALUES (37, 'Teknoloji Ýnceleme', 'Murat Arslan', 'Yeni teknolojik ürünler ve incelemeleri.', 'Teknoloji');
INSERT INTO Podcast VALUES (38, 'Motivasyon Hikayeleri', 'Zeynep Demir', 'Baþarý ve motivasyon üzerine hikayeler.', 'Kiþisel Geliþim');
INSERT INTO Podcast VALUES (39, 'Sanat Tarihi', 'Sibel Öztürk', 'Sanat tarihinin önemli noktalarý.', 'Sanat');
INSERT INTO Podcast VALUES (40, 'Giriþimcilik Hikayeleri', 'Elif Þahin', 'Baþarýlý giriþimcilerin hikayeleri.', 'Ýþ');
INSERT INTO Podcast VALUES (41, 'Teknoloji Sohbetleri', 'Ahmet Arslan', 'Teknoloji dünyasýnýn güncel konularý.', 'Teknoloji');
INSERT INTO Podcast VALUES (42, 'Saðlýklý Beslenme', 'Ayþe Yýldýz', 'Beslenme ve diyet üzerine bilgiler.', 'Saðlýk');
INSERT INTO Podcast VALUES (43, 'Tarih Anlatýlarý', 'Mehmet Kaya', 'Tarihin bilinmeyen hikayeleri.', 'Tarih');
INSERT INTO Podcast VALUES (44, 'Kitap Ýncelemesi', 'Burcu Þahin', 'Popüler kitaplarýn detaylý incelemeleri.', 'Edebiyat');
INSERT INTO Podcast VALUES (45, 'Spor Sohbetleri', 'Caner Demir', 'Spor dünyasýndan güncel haberler.', 'Spor');
INSERT INTO Podcast VALUES (46, 'Film Sohbetleri', 'Deniz Yýldýz', 'Sinema dünyasýndan sohbetler.', 'Sinema');
INSERT INTO Podcast VALUES (47, 'Kariyer Tüyolarý', 'Merve Þahin', 'Ýþ dünyasýnda ilerleme stratejileri.', 'Ýþ');
INSERT INTO Podcast VALUES (48, 'Lezzetli Tarifler', 'Fatma Arslan', 'Pratik yemek tarifleri.', 'Yemek');
INSERT INTO Podcast VALUES (49, 'Müzik Dünyasý', 'Serkan Yýlmaz', 'Müzik sektörü haberleri.', 'Müzik');
INSERT INTO Podcast VALUES (50, 'Kiþisel Geliþim Sohbetleri', 'Deniz Demir', 'Motivasyon ve geliþim üzerine.', 'Kiþisel Geliþim');
INSERT INTO Podcast VALUES (51, 'Haber Analizi', 'Emre Þahin', 'Güncel haberlerin analizi.', 'Haber');
INSERT INTO Podcast VALUES (52, 'Psikoloji Günlüðü', 'Ece Yýldýz', 'Psikolojik geliþmeler ve öneriler.', 'Psikoloji');
INSERT INTO Podcast VALUES (53, 'Bilim Haberleri', 'Seda Kaya', 'Bilim dünyasýndan son haberler.', 'Bilim');
INSERT INTO Podcast VALUES (54, 'Moda Dünyasý', 'Nilay Arslan', 'Moda dünyasýndan geliþmeler.', 'Moda');
INSERT INTO Podcast VALUES (55, 'Finansal Haberler', 'Ali Yýldýz', 'Ekonomi ve finans haberleri.', 'Finans');
INSERT INTO Podcast VALUES (56, 'Seyahat Notlarý', 'Ayhan Demir', 'Gezginlerin deneyimleri.', 'Seyahat');
INSERT INTO Podcast VALUES (57, 'Teknoloji Haberleri', 'Murat Þahin', 'Teknolojideki son geliþmeler.', 'Teknoloji');
INSERT INTO Podcast VALUES (58, 'Motivasyon Konuþmalarý', 'Zeynep Arslan', 'Baþarý ve motivasyon konularý.', 'Kiþisel Geliþim');
INSERT INTO Podcast VALUES (59, 'Sanat Sohbetleri', 'Sibel Demir', 'Sanat dünyasýndan sohbetler.', 'Sanat');
INSERT INTO Podcast VALUES (60, 'Giriþimcilik Fikirleri', 'Elif Yýlmaz', 'Yeni iþ fikirleri ve öneriler.', 'Ýþ');
INSERT INTO Podcast VALUES (61, 'Teknoloji Trendleri', 'Ahmet Þahin', 'Teknolojideki yeni trendler.', 'Teknoloji');
INSERT INTO Podcast VALUES (62, 'Saðlýklý Yaþam Tavsiyeleri', 'Ayþe Arslan', 'Yaþam kalitesini artýrma önerileri.', 'Saðlýk');
INSERT INTO Podcast VALUES (63, 'Tarih ve Kültür', 'Mehmet Þahin', 'Kültürel ve tarihi keþifler.', 'Tarih');
INSERT INTO Podcast VALUES (64, 'Kitap Dünyasý', 'Burcu Yýlmaz', 'Kitap dünyasýndan haberler.', 'Edebiyat');
INSERT INTO Podcast VALUES (65, 'Spor Analizleri', 'Caner Þahin', 'Spor müsabakalarýnýn analizi.', 'Spor');
INSERT INTO Podcast VALUES (66, 'Sinema Ýncelemesi', 'Deniz Arslan', 'Filmler ve sinema eleþtirileri.', 'Sinema');
INSERT INTO Podcast VALUES (67, 'Kariyer Geliþimi', 'Merve Yýldýz', 'Profesyonel geliþim yollarý.', 'Ýþ');
INSERT INTO Podcast VALUES (68, 'Yemek ve Tatlar', 'Fatma Þahin', 'Lezzetli yemek tarifleri.', 'Yemek');
INSERT INTO Podcast VALUES (69, 'Müzik ve Hikayeler', 'Serkan Demir', 'Müzik dünyasýnýn öyküleri.', 'Müzik');
INSERT INTO Podcast VALUES (70, 'Kiþisel Geliþim Tavsiyeleri', 'Deniz Arslan', 'Geliþim ve motivasyon.', 'Kiþisel Geliþim');
INSERT INTO Podcast VALUES (71, 'Haber Yorumlarý', 'Emre Yýlmaz', 'Güncel haberlerin yorumlarý.', 'Haber');
INSERT INTO Podcast VALUES (72, 'Psikoloji Sohbetleri', 'Ece Þahin', 'Zihinsel saðlýk konularý.', 'Psikoloji');
INSERT INTO Podcast VALUES (73, 'Bilimsel Geliþmeler', 'Seda Arslan', 'Bilim dünyasýndan geliþmeler.', 'Bilim');
INSERT INTO Podcast VALUES (74, 'Moda ve Stil', 'Nilay Þahin', 'Moda ve stil önerileri.', 'Moda');
INSERT INTO Podcast VALUES (75, 'Finans ve Yatýrým', 'Ali Þahin', 'Yatýrým ve finans stratejileri.', 'Finans');
INSERT INTO Podcast VALUES (76, 'Seyahat Hikayeleri', 'Ayhan Arslan', 'Gezginlerin ilginç hikayeleri.', 'Seyahat');
INSERT INTO Podcast VALUES (77, 'Teknoloji ve Yenilik', 'Murat Yýlmaz', 'Yenilikçi teknoloji konularý.', 'Teknoloji');
INSERT INTO Podcast VALUES (78, 'Motivasyon Zamaný', 'Zeynep Þahin', 'Günlük motivasyon ve baþarý.', 'Kiþisel Geliþim');
INSERT INTO Podcast VALUES (79, 'Sanat ve Tarih', 'Sibel Yýlmaz', 'Sanat ve tarih kesiþimi.', 'Sanat');
INSERT INTO Podcast VALUES (80, 'Giriþimcilik Hikayeleri', 'Elif Arslan', 'Baþarýlý giriþimci öyküleri.', 'Ýþ');
INSERT INTO Podcast VALUES (81, 'Teknoloji Gezegeni', 'Ahmet Demir', 'Teknoloji dünyasýndan haberler.', 'Teknoloji');
INSERT INTO Podcast VALUES (82, 'Saðlýklý Yaþam Önerileri', 'Ayþe Yýlmaz', 'Saðlýk ve yaþam önerileri.', 'Saðlýk');
INSERT INTO Podcast VALUES (83, 'Tarih Anlatýlarý', 'Mehmet Arslan', 'Tarihin ilginç anekdotlarý.', 'Tarih');
INSERT INTO Podcast VALUES (84, 'Kitap ve Edebiyat', 'Burcu Þahin', 'Edebiyat dünyasýndan haberler.', 'Edebiyat');
INSERT INTO Podcast VALUES (85, 'Spor ve Performans', 'Caner Yýlmaz', 'Spor performans analizleri.', 'Spor');
INSERT INTO Podcast VALUES (86, 'Sinema ve Dizi', 'Deniz Þahin', 'Sinema ve dizi eleþtirileri.', 'Sinema');
INSERT INTO Podcast VALUES (87, 'Kariyer ve Ýþ Dünyasý', 'Merve Demir', 'Kariyer yönetimi.', 'Ýþ');
INSERT INTO Podcast VALUES (88, 'Yemek Tarifleri', 'Fatma Yýldýz', 'Enfes yemek tarifleri.', 'Yemek');
INSERT INTO Podcast VALUES (89, 'Müzik ve Sanat', 'Serkan Þahin', 'Müzik ve sanat haberleri.', 'Müzik');
INSERT INTO Podcast VALUES (90, 'Kiþisel Geliþim Hikayeleri', 'Deniz Yýlmaz', 'Motivasyon ve geliþim hikayeleri.', 'Kiþisel Geliþim');
INSERT INTO Podcast VALUES (91, 'Güncel Haberler', 'Emre Arslan', 'Türkiye ve dünya haberleri.', 'Haber');
INSERT INTO Podcast VALUES (92, 'Psikoloji ve Zihin', 'Ece Demir', 'Zihinsel saðlýk konularý.', 'Psikoloji');
INSERT INTO Podcast VALUES (93, 'Bilim ve Teknoloji', 'Seda Þahin', 'Bilim ve teknoloji haberleri.', 'Bilim');
INSERT INTO Podcast VALUES (94, 'Moda ve Trendler', 'Nilay Demir', 'Moda dünyasýndan geliþmeler.', 'Moda');
INSERT INTO Podcast VALUES (95, 'Finansal Analiz', 'Ali Arslan', 'Ekonomi ve finans analizleri.', 'Finans');
INSERT INTO Podcast VALUES (96, 'Seyahat ve Keþif', 'Ayhan Þahin', 'Gezginlerin seyahat notlarý.', 'Seyahat');
INSERT INTO Podcast VALUES (97, 'Teknoloji ve Gelecek', 'Murat Demir', 'Geleceðin teknolojileri.', 'Teknoloji');
INSERT INTO Podcast VALUES (98, 'Motivasyon ve Baþarý', 'Zeynep Yýlmaz', 'Baþarý ve motivasyon üzerine.', 'Kiþisel Geliþim');
INSERT INTO Podcast VALUES (99, 'Sanat ve Kültür', 'Sibel Arslan', 'Sanat ve kültür sohbetleri.', 'Sanat');
INSERT INTO Podcast VALUES (100, 'Giriþimcilik Fikirleri', 'Elif Demir', 'Yeni giriþimcilik fikirleri.', 'Ýþ');
