INSERT INTO Sarkýcý VALUES (1, 'Deniz Arman', 'Pop müziðin genç yeteneklerinden.', 230000);
INSERT INTO Sarkýcý VALUES (2, 'Lina Kaya', 'Alternatif müzik tarzýyla tanýnýr.', 190000);
INSERT INTO Sarkýcý VALUES (3, 'Mertcan Soylu', 'Rock tarzýnda çýkýþ yapmýþtýr.', 150000);
INSERT INTO Sarkýcý VALUES (4, 'Elif Güneþ', 'Duygusal þarkýlarýyla bilinir.', 275000);
INSERT INTO Sarkýcý VALUES (5, 'Rüya Demir', 'R&B ve soul müzikte baþarýlýdýr.', 310000);
INSERT INTO Sarkýcý VALUES (6, 'Baran Kýlýç', 'Elektronik müzik prodüktörüdür.', 205000);
INSERT INTO Sarkýcý VALUES (7, 'Alya Yýlmaz', 'Söz yazarý ve indie sanatçýsýdýr.', 145000);
INSERT INTO Sarkýcý VALUES (8, 'Yiðit Tunç', 'Rap müziðiyle tanýnýr.', 420000);
INSERT INTO Sarkýcý VALUES (9, 'Sibel Ulu', 'Arabesk-pop karýþýmý müzik yapar.', 165000);
INSERT INTO Sarkýcý VALUES (10, 'Kerem Aksu', 'DJ ve prodüktör olarak bilinir.', 370000);
INSERT INTO Sarkýcý VALUES (11, 'Hazal Toprak', 'Klasik müzik eðitimlidir.', 98000);
INSERT INTO Sarkýcý VALUES (12, 'Oðuz Demirtaþ', 'Sahne performanslarýyla ünlüdür.', 198000);
INSERT INTO Sarkýcý VALUES (13, 'Melek Çaðlar', 'Jazz türünde yorumlarý vardýr.', 112000);
INSERT INTO Sarkýcý VALUES (14, 'Tunahan D.', 'Underground rap sahnesindendir.', 89000);
INSERT INTO Sarkýcý VALUES (15, 'Selin Ada', 'Genç kuþaðýn folk müzik temsilcisi.', 133000);
INSERT INTO Sarkýcý VALUES (16, 'Arda Bilgin', '90’lar pop tarzýný modernleþtirir.', 158000);
INSERT INTO Sarkýcý VALUES (17, 'Cemre Aksoy', 'Lirikal yazýmý güçlüdür.', 144000);
INSERT INTO Sarkýcý VALUES (18, 'Fýrat Özgür', 'Kendine has vokal tonuna sahiptir.', 207000);
INSERT INTO Sarkýcý VALUES (19, 'Gizem Y.', 'Sahne adýyla GZY olarak bilinir.', 262000);
INSERT INTO Sarkýcý VALUES (20, 'Efe Kaan', 'Elektro-pop müzik üreticisidir.', 195000);
INSERT INTO Sarkýcý VALUES (21, 'Melisa Ay', 'Yumuþak vokalleriyle tanýnýr.', 165000);
INSERT INTO Sarkýcý VALUES (22, 'Kaan Karaca', 'Çok dilli þarkýlar söyler.', 180000);
INSERT INTO Sarkýcý VALUES (23, 'Seray Çetin', 'Anadolu ezgilerini iþler.', 122000);
INSERT INTO Sarkýcý VALUES (24, 'Emir Yýldýrým', 'Klasik rock yorumcusudur.', 132000);
INSERT INTO Sarkýcý VALUES (25, 'Nazlý Bora', 'Dijital platformlarda ünlü oldu.', 228000);
INSERT INTO Sarkýcý VALUES (26, 'Cenk Uluç', 'Albümleriyle ödüller kazanmýþtýr.', 255000);
INSERT INTO Sarkýcý VALUES (27, 'Beril Güler', 'Lofi tarzýnda üretim yapar.', 118000);
INSERT INTO Sarkýcý VALUES (28, 'Tolga Uður', 'Elektronik altyapýlar kullanýr.', 143000);
INSERT INTO Sarkýcý VALUES (29, 'Ýrem Can', 'Genç yaþta müzik kariyerine baþladý.', 215000);
INSERT INTO Sarkýcý VALUES (30, 'Ömer Ayaz', 'Tiyatro kökenli bir sanatçýdýr.', 108000);
INSERT INTO Sarkýcý VALUES (31, 'Lara Duru', 'Trap-pop alanýnda öne çýktý.', 242000);
INSERT INTO Sarkýcý VALUES (32, 'Yusuf Alp', 'Gitarist ve söz yazarýdýr.', 152000);
INSERT INTO Sarkýcý VALUES (33, 'Asya Nur', 'Klasik Türk müziði icra eder.', 97000);
INSERT INTO Sarkýcý VALUES (34, 'Tuna K.', 'Müzik teknolojileriyle ilgilenir.', 163000);
INSERT INTO Sarkýcý VALUES (35, 'Neval G.', 'YouTube çýkýþlý sanatçýdýr.', 184000);
INSERT INTO Sarkýcý VALUES (36, 'Çaðrý Eren', 'Festival sahnelerinde yer alýr.', 121000);
INSERT INTO Sarkýcý VALUES (37, 'Ýdil Ceylan', 'Söz yazarý ve yorumcudur.', 157000);
INSERT INTO Sarkýcý VALUES (38, 'Okan Uz', 'Ses aralýðý geniþtir.', 167000);
INSERT INTO Sarkýcý VALUES (39, 'Buse Naz', 'Yeni nesil pop dalgasýndandýr.', 230000);
INSERT INTO Sarkýcý VALUES (40, 'Serhat D.', 'Çok sayýda düet çalýþmasý vardýr.', 196000);
INSERT INTO Sarkýcý VALUES (41, 'Elanur T.', 'Lirik trap müzikte öne çýkar.', 274000);
INSERT INTO Sarkýcý VALUES (42, 'Bartu Alp', 'Jazz-fusion denemeleri yapar.', 99000);
INSERT INTO Sarkýcý VALUES (43, 'Miraç Cihan', 'Rap battle geçmiþi vardýr.', 221000);
INSERT INTO Sarkýcý VALUES (44, 'Pelin K.', 'Slow müzikte uzmanlaþmýþtýr.', 119000);
INSERT INTO Sarkýcý VALUES (45, 'Yaren S.', 'Kendi bestelerini seslendirir.', 138000);
INSERT INTO Sarkýcý VALUES (46, 'Hakan Gür', 'Söz yazarý ve aranjördür.', 175000);
INSERT INTO Sarkýcý VALUES (47, 'Nilay Duru', 'Halk müziðine modern yorumlar katar.', 99000);
INSERT INTO Sarkýcý VALUES (48, 'Tunç Bora', 'Alternatif sahnelerde çalar.', 126000);
INSERT INTO Sarkýcý VALUES (49, 'Derya Sönmez', 'Sahne enerjisiyle bilinir.', 184000);
INSERT INTO Sarkýcý VALUES (50, 'Sarp Uysal', 'Tanýnmýþ pop yýldýzýdýr.', 310000);
INSERT INTO Sarkýcý VALUES (51, 'Sena Gül', 'Pop-folk karýþýmý þarkýlarýyla öne çýkar.', 164000);
INSERT INTO Sarkýcý VALUES (52, 'Onur Erkan', 'Yavaþ tempolu aþk þarkýlarýyla tanýnýr.', 179000);
INSERT INTO Sarkýcý VALUES (53, 'Dilara Soydan', 'Tiyatro müzikleriyle de ilgilenir.', 102000);
INSERT INTO Sarkýcý VALUES (54, 'Ali Deniz', 'Kendi beste ve düzenlemeleriyle bilinir.', 243000);
INSERT INTO Sarkýcý VALUES (55, 'Eylül Aslan', 'Alternatif sahnelerin sevilen ismidir.', 151000);
INSERT INTO Sarkýcý VALUES (56, 'Volkan G.', 'DJ ve vokalist olarak sahne alýr.', 186000);
INSERT INTO Sarkýcý VALUES (57, 'Sude Tekin', 'Feminist temalý þarkýlar üretir.', 122000);
INSERT INTO Sarkýcý VALUES (58, 'Enes Vural', 'Ýngilizce ve Türkçe þarkýlar söyler.', 215000);
INSERT INTO Sarkýcý VALUES (59, 'Berna K.', 'Anadolu rock müziðiyle ilgilenir.', 98000);
INSERT INTO Sarkýcý VALUES (60, 'Kývanç Y.', 'Karma türlerde müzik üretir.', 194000);
INSERT INTO Sarkýcý VALUES (61, 'Hazal Ýnce', 'Minimalist altyapýlara sahiptir.', 87000);
INSERT INTO Sarkýcý VALUES (62, 'Ayberk K.', 'Hip-hop kültürünün içinden gelir.', 248000);
INSERT INTO Sarkýcý VALUES (63, 'Gülce A.', 'Ses rengiyle fark yaratýr.', 173000);
INSERT INTO Sarkýcý VALUES (64, 'Mert Aydýn', 'Rock sahnesinin dinamik ismidir.', 138000);
INSERT INTO Sarkýcý VALUES (65, 'Selin Barlas', 'Piyano eþliðinde þarkýlar söyler.', 159000);
INSERT INTO Sarkýcý VALUES (66, 'Arif Mert', 'Söz yazarlýðý yönü güçlüdür.', 205000);
INSERT INTO Sarkýcý VALUES (67, 'Ýlke Naz', 'Elektro-ambient türünde parçalar üretir.', 128000);
INSERT INTO Sarkýcý VALUES (68, 'Ekin Y.', 'Kýsa þarkýlarýyla TikTok’ta ün kazandý.', 191000);
INSERT INTO Sarkýcý VALUES (69, 'Zeynep T.', 'Rap müziði kadýn temsilcisidir.', 236000);
INSERT INTO Sarkýcý VALUES (70, 'Taner Koç', 'Rock-opera denemeleri yapar.', 105000);
INSERT INTO Sarkýcý VALUES (71, 'Beren Sarý', 'Vokal gücüyle dikkat çeker.', 144000);
INSERT INTO Sarkýcý VALUES (72, 'Orkun Kaya', 'Elektronik tabanlý aþk þarkýlarýyla tanýnýr.', 169000);
INSERT INTO Sarkýcý VALUES (73, 'Aslý Mavi', 'Ege ezgilerini günümüz müziðine taþýr.', 134000);
INSERT INTO Sarkýcý VALUES (74, 'Fatih Arda', 'Underground techno prodüktörüdür.', 152000);
INSERT INTO Sarkýcý VALUES (75, 'Janset K.', 'Yavaþ ve derin parçalarýyla ünlüdür.', 146000);
INSERT INTO Sarkýcý VALUES (76, 'Uðurhan D.', 'Popüler düetleriyle tanýnýr.', 231000);
INSERT INTO Sarkýcý VALUES (77, 'Yasemin Güçlü', 'Etno caz tarzýnda iþler yapar.', 87000);
INSERT INTO Sarkýcý VALUES (78, 'Samet Y.', 'Baðýmsýz sahnelerde öne çýktý.', 124000);
INSERT INTO Sarkýcý VALUES (79, 'Ahu P.', 'Yeni nesil pop vokalistidir.', 158000);
INSERT INTO Sarkýcý VALUES (80, 'Cem Turgay', 'Kendi beste stüdyosu vardýr.', 211000);
INSERT INTO Sarkýcý VALUES (81, 'Melis Z.', 'Þiirsel þarký sözleriyle dikkat çeker.', 129000);
INSERT INTO Sarkýcý VALUES (82, 'Taylan A.', 'Rap ve spoken word arasýnda eserler üretir.', 177000);
INSERT INTO Sarkýcý VALUES (83, 'Nisa Elvan', 'Lise yýllarýndan beri müzikle ilgilenir.', 148000);
INSERT INTO Sarkýcý VALUES (84, 'Burak K.', 'Elektronik müzik festivallerinde yer alýr.', 165000);
INSERT INTO Sarkýcý VALUES (85, 'Ezgi Polat', 'Kendine özgü týnýsýyla bilinir.', 136000);
INSERT INTO Sarkýcý VALUES (86, 'Alp Cihan', 'Progresif rock sahnesindedir.', 190000);
INSERT INTO Sarkýcý VALUES (87, 'Sibel Naz', 'Çocuk þarkýlarý albümleri yapar.', 92000);
INSERT INTO Sarkýcý VALUES (88, 'Halil Ýbrahim G.', 'Sosyal mesaj içerikli þarkýlar yazar.', 117000);
INSERT INTO Sarkýcý VALUES (89, 'Dila Nur', 'Vokal ve prodüksiyon becerisine sahiptir.', 189000);
INSERT INTO Sarkýcý VALUES (90, 'Emin Aydýn', 'Klasik müzik altyapýsý olan modern eserler üretir.', 103000);
INSERT INTO Sarkýcý VALUES (91, 'Yelda A.', 'Müziðe resimle beraber yaklaþýr.', 98000);
INSERT INTO Sarkýcý VALUES (92, 'Ozan Erbay', 'Üniversite müzik kulübünden çýkar.', 111000);
INSERT INTO Sarkýcý VALUES (93, 'Lale Çelik', 'Yavaþ tempolu aþk þarkýlarýnda baþarýlýdýr.', 142000);
INSERT INTO Sarkýcý VALUES (94, 'Çaðan Y.', 'Söz yazýmý kadar sahne tasarýmýyla da ilgilenir.', 163000);
INSERT INTO Sarkýcý VALUES (95, 'Beliz T.', 'Sosyal medya sayesinde tanýndý.', 198000);
INSERT INTO Sarkýcý VALUES (96, 'Süheyla K.', 'Klasik Türk müziði yorumcusu.', 87000);
INSERT INTO Sarkýcý VALUES (97, 'Kenan Baþar', 'Baðýmsýz yayýncý olarak müzik yapar.', 125000);
INSERT INTO Sarkýcý VALUES (98, 'Tuana Y.', 'Romantik slow türlerde þarkýlar söyler.', 139000);
INSERT INTO Sarkýcý VALUES (99, 'Nihat Soylu', 'Gitarist olarak sahne aldýktan sonra solo kariyere geçti.', 157000);
INSERT INTO Sarkýcý VALUES (100, 'Zara A.', 'Ünlü bir müzik okulundan mezundur.', 214000);
